name = "UnscentedTransforms"
uuid = "fb6c460f-f05e-49c3-9e45-b6a440335337"
version = "0.2.0"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
